### PR TITLE
[WIP] Tilios correction

### PR DESCRIPTION
**Pull request by FrancoisDupayrat**
For Issue #43 
Work In Progress because the article is too long to correct in one sitting.

Corrected until line 96 so far.

I took the initiative of saying "Tiers-Lieu" all the time.

What is the meaning of "rélaisée" line 94? I suspect a typo, but have no clue what you wanted to say.

### CODE REVIEW

**Comment by FrancoisDupayrat** [comment]
That was a work in progress :/

**Comment by XavCC** [comment]
You can Start [WIP 2] ;-)

**Comment by FrancoisDupayrat** [comment]
Then [WIP 3], then [WIP final], then [WIP final final] then [WIP final release] ? ^^ 
That defeats the purpose of using Github, where you can continue pushing on an opened PR.

The goal of opening an unfinished PR is to signal that I'm working on it, show the progress and start a discussion.

Still waiting for your answer on the discussion part by the way ;)

**Comment by XavCC** [comment]
Ok ! 
I will respect your purpose for the next PR.

About your questions : 
+ Tiers-Lieux is used for libre et open source, tiers-lieu is used for basical concept 
+ Line 94, you were right. I corrected it

And I also continued writing the text

**Pull request merged**
